### PR TITLE
changed endpoint for setup api

### PR DESCRIPTION
**Pull request by MuskanPaliwal**
## Summary by CodeRabbit

- **Refactor**
	- Updated the method for fetching tracked repositories to enhance compatibility with different hosting services.

### CODE REVIEW

**Comment by tapishr** [comment]
To be tested on github latest UI

**Review by avikalpg — APPROVED** [review]
I thought that we have a backwards compatible way of doing this. But I think this works.

**Comment by avikalpg** [comment]
> To be tested on github latest UI

That we can merge in another PR. For now, this should work for users not on the beta feature.

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Code Coverage |
| -------------- | --------------- |
| tapish303@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

Code coverage is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/settings)

**Pull request merged**
